# Generated by Django 5.1.4 on 2025-01-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography_Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по годам')),
                ('salary_data', models.TextField(verbose_name='Таблица зарплат по годам')),
                ('vacancy_chart', models.ImageField(upload_to='', verbose_name='График количества вакансий по годам')),
                ('vacancy_data', models.TextField(verbose_name='Таблица количества вакансий по годам')),
            ],
            options={
                'verbose_name': 'География',
            },
        ),
        migrations.CreateModel(
            name='Main_Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по годам')),
                ('salary_data', models.TextField(verbose_name='Таблица зарплат по годам')),
                ('vacancy_chart', models.ImageField(upload_to='', verbose_name='График количества вакансий по годам')),
                ('vacancy_data', models.TextField(verbose_name='Таблица количества вакансий по годам')),
                ('city_salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по городам')),
                ('city_salary_data', models.TextField(verbose_name='Таблица зарплат по городам')),
                ('city_vacancy_share_chart', models.ImageField(upload_to='', verbose_name='График долей вакансий по городам')),
                ('city_vacancy_share_data', models.TextField(verbose_name='Таблица доли вакансий по городам')),
                ('top_skills_2015_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2015 год')),
                ('top_skills_2015_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2015 год')),
                ('top_skills_2016_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2016 год')),
                ('top_skills_2016_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2016 год')),
                ('top_skills_2017_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2017 год')),
                ('top_skills_2017_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2017 год')),
                ('top_skills_2018_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2018 год')),
                ('top_skills_2018_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2018 год')),
                ('top_skills_2019_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2019 год')),
                ('top_skills_2019_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2019 год')),
                ('top_skills_2020_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2020 год')),
                ('top_skills_2020_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2020 год')),
                ('top_skills_2021_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2021 год')),
                ('top_skills_2021_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2021 год')),
                ('top_skills_2022_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2022 год')),
                ('top_skills_2022_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2022 год')),
                ('top_skills_2023_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2023 год')),
                ('top_skills_2023_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2023 год')),
                ('top_skills_2024_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2024 год')),
                ('top_skills_2024_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2024 год')),
            ],
            options={
                'verbose_name': 'Общая статистика',
            },
        ),
        migrations.CreateModel(
            name='Relevance_Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_salary_chart', models.ImageField(upload_to='', verbose_name='График зарплат по годам для выбранной профессии ')),
                ('profession_salary_data', models.TextField(verbose_name='Таблица зарплат по годам для выбранной профессии ')),
                ('profession_vacancy_chart', models.ImageField(upload_to='', verbose_name='График количества вакансий по годам для выбранной профессии ')),
                ('profession_vacancy_data', models.TextField(verbose_name='Таблица количества вакансий по годам для выбранной профессии ')),
            ],
            options={
                'verbose_name': 'Востребованность',
            },
        ),
        migrations.CreateModel(
            name='Skills_Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_skills_2015_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2015 год')),
                ('top_skills_2015_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2015 год')),
                ('top_skills_2016_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2016 год')),
                ('top_skills_2016_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2016 год')),
                ('top_skills_2017_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2017 год')),
                ('top_skills_2017_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2017 год')),
                ('top_skills_2018_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2018 год')),
                ('top_skills_2018_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2018 год')),
                ('top_skills_2019_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2019 год')),
                ('top_skills_2019_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2019 год')),
                ('top_skills_2020_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2020 год')),
                ('top_skills_2020_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2020 год')),
                ('top_skills_2021_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2021 год')),
                ('top_skills_2021_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2021 год')),
                ('top_skills_2022_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2022 год')),
                ('top_skills_2022_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2022 год')),
                ('top_skills_2023_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2023 год')),
                ('top_skills_2023_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2023 год')),
                ('top_skills_2024_chart', models.ImageField(upload_to='', verbose_name='График ТОП-20 навыков за 2024 год')),
                ('top_skills_2024_data', models.TextField(verbose_name='Таблица ТОП-20 навыков за 2024 год')),
            ],
            options={
                'verbose_name': 'Навыки',
            },
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
