# Generated by Django 5.1.4 on 2025-01-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_statistics', '0002_geography_statistics_main_statistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography_statistics',
            name='salary_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Уровень зарплат по городам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='geography_statistics',
            name='salary_data',
            field=models.TextField(blank=True, verbose_name='Таблица Уровень зарплат по городам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='geography_statistics',
            name='vacancy_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Доля вакансий по городам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='geography_statistics',
            name='vacancy_data',
            field=models.TextField(blank=True, verbose_name='Таблица Доля вакансий по городам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='city_salary_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Уровень зарплат по городам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='city_salary_data',
            field=models.TextField(blank=True, verbose_name='Таблица Уровень зарплат по городам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='city_vacancy_share_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Доля вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='city_vacancy_share_data',
            field=models.TextField(blank=True, verbose_name='Таблица Доля вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='salary_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Динамика уровня зарплат по годам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='salary_data',
            field=models.TextField(blank=True, verbose_name='Таблица Динамика уровня зарплат по годам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2015_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2015 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2015_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2015 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2016_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2016 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2016_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2016 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2017_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2017 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2017_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2017 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2018_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2018 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2018_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2018 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2019_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2019 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2019_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2019 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2020_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2020 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2020_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2020 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2021_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2021 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2021_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2021 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2022_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2022 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2022_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2022 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2023_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2023 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2023_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2023 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2024_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2024 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='top_skills_2024_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2024 год'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='vacancy_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Динамика уровня зарплат по годам'),
        ),
        migrations.AlterField(
            model_name='main_statistics',
            name='vacancy_data',
            field=models.TextField(blank=True, verbose_name='Таблица Динамика уровня зарплат по годам'),
        ),
        migrations.AlterField(
            model_name='relevance_statistics',
            name='profession_salary_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Динамика уровня зарплат по годам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='relevance_statistics',
            name='profession_salary_data',
            field=models.TextField(blank=True, verbose_name='Таблица Динамика уровня зарплат по годам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='relevance_statistics',
            name='profession_vacancy_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График Динамика количества вакансий по годам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='relevance_statistics',
            name='profession_vacancy_data',
            field=models.TextField(blank=True, verbose_name='Таблица Динамика количества вакансий по годам для выбранной профессии'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2015_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2015 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2015_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2015 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2016_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2016 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2016_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2016 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2017_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2017 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2017_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2017 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2018_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2018 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2018_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2018 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2019_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2019 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2019_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2019 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2020_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2020 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2020_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2020 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2021_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2021 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2021_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2021 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2022_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2022 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2022_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2022 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2023_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2023 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2023_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2023 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2024_chart',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График ТОП-20 навыков за 2024 год'),
        ),
        migrations.AlterField(
            model_name='skills_statistics',
            name='top_skills_2024_data',
            field=models.TextField(blank=True, verbose_name='Таблица ТОП-20 навыков за 2024 год'),
        ),
    ]
